export const actionTypes = {
    GET_DATA_POKEMON_REQUEST: 'GET_DATA_POKEMON_REQUEST',
    GET_DATA_POKEMON_SUCCESS: 'GET_DATA_POKEMON_SUCCESS',
    GET_DATA_POKEMON_FAILED: 'GET_DATA_POKEMON_FAILED',
  };